### ISSUE TITLE
Dev Tasks - Admin User Story 2 - Publish and Modify Catalog Items - Parent Issue #7

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#102]

**Comment by davidatfei** [comment]
This is implemented and testable. However, the db schema is from early in the week. Some work still needs to be done to include changes that were made to the db schema this week.

**Comment by davidatfei** [comment]
Updated db schema to match v5 of spreadsheet. Added rudimentary paging to table. Still need to add filter.

**Comment by davidatfei** [comment]
Added filtering and sorting of items.
