### ISSUE TITLE
Dev Tasks - Admin User Story 4 - Delete Products and Services from Catalog - Parent Issue #115

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#104]

**Comment by davidatfei** [comment]
This feature is implemented and testable. Some UI styling still needs to occur.

**Comment by davidatfei** [comment]
This is implemented and testable. However, the db schema is from early in the week. Some work still needs to be done to include changes that were made to the db schema this week.

**Comment by davidatfei** [comment]
Tested and working after modifications following the schema changes.
