### ISSUE TITLE
Dev Tasks - Admin User Story 3 - Bulk Import Catalog Items - Parent Issue #27

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#108]

**Comment by davidatfei** [comment]
This feature has been implemented and is testable. However, it was implemented using the db schema from early in the week. Changes are required to include schema changes that were made during the week.

**Comment by davidatfei** [comment]
This feature is working and is current as of the v5 version of the sample spreadsheet data.
