### ISSUE TITLE
Admin User Story 7 - View Authorized Users' Orders

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#11]
As an administrator, I want to view active orders and order history by authorized users so I can approve/reject orders under review, cancel orders and provide support functions

Acceptance Criteria:
•	User can search for active orders by:
o	User
o	Order Date
o	Order #
o	Order Status
•	User can view a list of orders with following columns
o	User
o	Product(s)
o	Order Date
o	Order #
o	Order Total
o	Order Status
	Pending
	Confirmed
	Cancelled

**Comment by ClaireReinken** [comment]
This is covered through admin reporting.
