### ISSUE TITLE
Admin User Story 12 - Expenditures Over a Period of Time Report

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#111]
As an administrator, I want to see a reports that allows me to view expenditures over a period of time, so I can be aware of order expenditure history within a specified date range

Acceptance Criteria:
• Arrive at Reports Dashboard as an Administrator
• See an "Expenditures Over a Period of Time" panel
 - Preview displays a preview of the report as a table (see preview below) for the current fiscal quarter
• Click the panel opens the report in an overlay
• Results appear as rows in a table view (in ascending order by date) with the following columns:
     - Date
     - Order #
     - Total $ (for the order)
     - Account (Department)
• Column headers are sortable
• The final row is labeled Total and displays the Total sum of the "Total $" column
• Report header reads, "Expenditures Over [Start Date] - [End Date]"
• User can filter in/out departments and adjust date ranges
     - Start/End dates cannot be a future date
See mock up - 
![ca adpq time expend report mock up](https://cloud.githubusercontent.com/assets/22507054/23185276/e08b72ae-f850-11e6-9198-0aee567f8739.png)

**Comment by Mikewilburn302** [comment]
Is there any input or filters?

Are the columns sortable?

**Comment by ClaireReinken** [comment]
Is there any input or filters? - The user should be able to enter a start and end date for the report

Are the columns sortable? - Ideally, this report should be in Excel or CSV so the user can sort columns as needed.

**Comment by Mikewilburn302** [comment]
Does this mean that the report auto-exports? It is not visible within the application?

**Comment by ClaireReinken** [comment]
Does this mean that the report auto-exports? It is not visible within the application? - This report should be visible in the applicable with the ability to export the data to a .CSV or excel for further use.

**Comment by Mikewilburn302** [comment]
So if the report is visible within the application, how is sorting being done? Or can it only be sorted once exported to Excel?

**Comment by ClaireReinken** [comment]
So if the report is visible within the application, how is sorting being done? Or can it only be sorted once exported to Excel? Sorting only done in Excel

**Comment by davidatfei** [comment]
"Start/End dates cannot be a future date" is not enforced. In fact, the initial date range is the current quarter, which will almost always include an end date in the future.

Report is returned as an html table. It can be printed. It can be sorted on the page. Export is accomplished on the raw data tab, where a csv consumable by Excel can be "Download"ed. Raw data download includes additional columns.
