### ISSUE TITLE
Admin User Story 13 - Expenditures by Product Type Report

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#112]
As an administrator, I want to see a report that allows me to view expenditures broken up by product type, so I can be aware of expenditure by hardware, software and services

Acceptance Criteria:
• Arrive at Reports Dashboard as an Administrator
• See an "Expenditures by Product Type" panel
     - Preview of report displays in panel that shows a pie chart breaking down the total expenditures by Hardware, Software and Services for the current fiscal quarter
     - Total $ for each product type is also displayed for each section of the pie
• Clicking on the panel opens a larger version of the report in an overlay
• User can adjust date ranges
     - Start/End dates cannot be a future date
• Export button will export a .csv of the underlying data that makes up this report

**Comment by Mikewilburn302** [comment]
"Clicking on each section of the pie (Hardware, Software, Services)" - clicking on it does what exactly?

**Comment by ClaireReinken** [comment]
"Clicking on each section of the pie (Hardware, Software, Services)" - clicking on it does what exactly? - My type. Originally, I wanted to be able to drill-down on the product categories, but there are over 180 categories for hardware so that's not feasible. Clicking on each item will do nothing. I will update the acceptance criteria.

**Comment by davidatfei** [comment]
No 'dashboard'.
No 'larger version of the report'.
Future date restriction not enforced. In fact default date range (current quarter) almost always include a future end date.
Export available on the Raw Data tab as "Download".
