### ISSUE TITLE
Admin User Story 14 - Expenditures by Vendor Report

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#113]
As an administrator, I want to see a report that allows me to view expenditures broken up by vendor so I can be aware of the amount of money spent for each vendor in the system

Acceptance Criteria:
• Arrive at Reports Dashboard as an Administrator
• See an "Expenditures by Product Type" panel
     - Panel displays a preview of a bar chart which several vendors with three bars per vendor (different colors), each representing product types. Left part of graph represents total expenditures in $
• Clicking the panel will expand the report in an overlay
• User can filter vendors and product types in and out of the report and adjust date ranges
     - Start/End dates cannot be a future date

**Comment by davidatfei** [comment]
No 'dashboard'
No 'expand the report'
Only filter is date range. Extended filtering can be performed in Excel using downloaded raw data.
Future date restriction not enforced. Initial date range (current quarter) almost always includes a future end date.
