### ISSUE TITLE
Admin User Story 16 - Edit/Delete Items in a Catalog

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#115]
As an administrator, I want to be edit and delete existing products and services provided by state contracted vendors from the catalog so consumers can order items from an accurate catalog

Acceptance Criteria:
• User can access the catalog list
- User can search the list which will limit the values displayed
• User can edit and of the following data points of an item:
•CLIN [text field]
•UNPSC Code (Version 11) [text field]
•Manufacturer Part Number (OEM #) [text field]
•Manufacturer (OEM) [text field]
•SKU #/ Item # [text field]
•Item Name [text field]
•Item Description [text field]
•Unit of Measure (if applicable) [dropdown]
•List Price/MSRP [dollar]
•Contract Unit Price [dollar]
•Contract Discount [numeric]
•Category [predictive text-dropdown]
•Product Type [dropdown]
•Contract # [text]
•Contract Vendor [text]
•Contract Expiration Date [date]
•Product Image 

• User can delete one item in the list and receives a confirmation prompt before doing so

**Comment by ClaireReinken** [comment]
Dev and UI tasks for this issue are documented in #104 and #105

**Comment by neelusingh28** [comment]
User can search the list which will limit the values displayed - What does this mean? Which values will display in search results ? Will it be different from the above list?

**Comment by ClaireReinken** [comment]
User can search the list which will limit the values displayed - What does this mean? Which values will display in search results ? Will it be different from the above list? - This means the user will first see a table with the entire product catalog and they will be able to search for an item that will reduce the results displayed in the catalog table.
