### ISSUE TITLE
Drop down menu freezes when clicked

### ISSUE THREAD

**Issue by neelusingh28** [FEISystems/ca-adpq-prototype#119]
Once user clicks on Hardware or Services and then on any sub menu item then screen freezes there unless user goes back and click again on Hardware or Services. You may know it already but just wanted to pass across. 

![image](https://cloud.githubusercontent.com/assets/25771656/23267377/97211e70-f9b8-11e6-9c37-f804927da320.png)

**Comment by jennymnh** [comment]
@neelusingh28 , this is ready for testing once the site gets updated.

**Comment by neelusingh28** [comment]
This issue is resolved tested on both 5000 & 5001.
