### ISSUE TITLE
Inventory is NOT displaying as per the data set spreadsheet

### ISSUE THREAD

**Issue by neelusingh28** [FEISystems/ca-adpq-prototype#124]
For an example: If I filter on product type as hardware then under category desktop - We get 82 results but website displaying only 9 results.

Similarly power desktops are displaying only 3 however there are 5 in spreadsheet

Similarly Mobile Workstations is displaying only 1 however there are 4 in spreadsheet

**Comment by davidatfei** [comment]
Cannnot duplicate. Maybe try importing items again.

**Comment by neelusingh28** [comment]
1. Desktop Value Added Services are 8 in data set but displaying 6 on 5000 site. 
2. Laptop Value Added Services are 9 in data set but displaying 7 on 5000 site. 
3. All Value Added Services is blank on 5000 site.

**Comment by lutech** [comment]
@neelusingh28 , I sent you the category groupings. I don't think this is a bug. Can you confirm?

**Comment by neelusingh28** [comment]
@lutech, I tested as per the category groupings only. I observed these 3 are not displaying as expected.

**Comment by lutech** [comment]
![image](https://cloud.githubusercontent.com/assets/6694316/23485818/24ed07fe-feab-11e6-8877-0af4b4c617f4.png)
![image](https://cloud.githubusercontent.com/assets/6694316/23485837/4437d6ac-feab-11e6-9631-849a4cf57d01.png)


@neelusingh28 , For the first two, some products are skipped when uploaded because the price is "$-". If you take those into account, the numbers add up correctly. The All VAS is a back-end bug. 

@davidatfei , seem like filters don't like the characters "(" and ")". Can you please configure to accept these. thanks.

**Comment by davidatfei** [comment]
Luis, I just checked in a change that should address all special characters. Please give it a try. If you encounter problems with any other characters please let me know.

**Comment by lutech** [comment]
@davidatfei Thanks David, I confirmed its working now. Moving to QC.

**Comment by neelusingh28** [comment]
@lutech 
Browser: Chrome but have following issues now:
All Value Added Services is displaying now but 30 items however data set have 20
Desktop Value Added Services are 8 in data set but displaying 6 on 5000 site.
Laptop Value Added Services are 9 in data set but displaying 7 on 5000 site.

**Comment by neelusingh28** [comment]
Retested:

Desktop Value Added Services & Laptop Value Added Services are displaying as expected ignoring items with $0 price. Count is matching as per data set. 

but All Value Added Services are 18 in data set but displaying 30 on 5000 site.

**Comment by lutech** [comment]
@neelusingh28 , I was able to verify that there are 29 items that should be appearing in All VAS. Please see spreadsheet below.
![image](https://cloud.githubusercontent.com/assets/6694316/23540527/c246ffa0-ffaf-11e6-8dfd-eaa9b2c99a77.png)

However, the Yellow line is not showing up in the All VAS, but DOES show up in the advanced search. 
Adding @davidatfei , I don't know why this would be. Any ideas?

**Comment by davidatfei** [comment]
It is showing up on the 5000 server.

![basicdispositionon5000inallvas](https://cloud.githubusercontent.com/assets/25746847/23551514/02b3a162-ffe5-11e6-921f-9775b5c711bd.png)

**Comment by lutech** [comment]
Hi david, there should actually be two with the same Title but different CLIN. Can you also check the Product Details.

Thanks,

Luis Najera
Sr. UX Associate

office | 443.270.5108
fax | 410.715.6538
email | luis.najera@feisystems.com<mailto:luis.najera@feisystems.com>

FEi Systems
9755 Patuxent Woods Drive, Columbia, MD 21046 | www.FEIsystems.com<http://www.FEIsystems.com>




On Fri, Mar 3, 2017 at 7:43 AM -0500, "davidatfei" <notifications@github.com<mailto:notifications@github.com>> wrote:


It is showing up on the 5000 server.

[basicdispositionon5000inallvas]<https://cloud.githubusercontent.com/assets/25746847/23551514/02b3a162-ffe5-11e6-921f-9775b5c711bd.png>

**Comment by davidatfei** [comment]
I see. You are probably filtering on Category, and those two have different categories.  It's subtle, but one has a '-' while the other does not.

**Comment by davidatfei** [comment]
Never mind. I think I know what it is. Working on it now.

**Comment by davidatfei** [comment]
@lutech , I found the problem and a fix has been created.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site and working as expected in Chrome, Firefox, IE and devices.
