### ISSUE TITLE
Home Page Stock Art Needs to Be Revised

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#132]
The current images of generic products imply that we have sales and seem to be directed towards a more generic consumer rather than a government buyer. Can we replace these items with stock art of IT workers, people working on computers, people pulling stock from warehouses.

**Comment by kcallander** [comment]
These have been updated and new layouts need to be reviewed and approved.

**Comment by jennymnh** [comment]
Images have been revised and I have pushed my changes. The issue is related to #117 so I am closing this one.
