### ISSUE TITLE
About Us, Help Desk, and FAQ Link on Home Page Should Be Removed

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#133]
Please Keep Contact Us | Contact Information. Lisa will provide text for this link.

**Comment by neelusingh28** [comment]
@llin-freeman this is working as expected assigning to you for the text.

**Comment by llin-freeman** [comment]
Thanks! Please use:
Questions? Find an issue with this site? Please report it to: CA.BugReport@feisystems.com.

**Comment by jennymnh** [comment]
I have added the text to the page and checked it in.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.
