### ISSUE TITLE
Admin User Story 9 - View Overall Order Statistics

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#14]
As an administrator, I want to see a dashboard of reports that allow me to view expenditures over a period of time, expenditures by product type, expenditures by vendor and purchases by department over a period of so I can be aware of order statistics and trends

Acceptance Criteria:
•	Arrive at Reports Dashboard as an Administrator
•	See an "Expenditures Over a Period of Time" panel
•	See an "Expenditures by Product Type" panel
•	See an "Expenditures by Vendor" panel
•	See a "TRENDS: Purchases by Department" panel
See mock up - 
![ca adpq dashboard mock up](https://cloud.githubusercontent.com/assets/22507054/23221625/8b23ddda-f8f3-11e6-8860-0f861c9bed0f.png)

**Comment by neelusingh28** [comment]
Q1. Will there by drop down to choose product type?
Q2. Will there be check boxes to drill down the specific products?

**Comment by ClaireReinken** [comment]
Q1. Will there by drop down to choose product type? Yes
 Q2. Will there be check boxes to drill down the specific products? Yes

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues #106 and #107

**Comment by neelusingh28** [comment]
I'm assuming if incorrect product number or contract number entered in search box then system should display error message that "No results found. Please try another search."

**Comment by jennymnh** [comment]
After I search by these filters (the acceptance criterias), what other type of information would show? I would need to know what types of fields go into an order/expenditure report so I could mock it up.

**Comment by ClaireReinken** [comment]
I'm assuming if incorrect product number or contract number entered in search box then system should display error message that "No results found. Please try another search." - Correct

**Comment by ClaireReinken** [comment]
After I search by these filters (the acceptance criteria's), what other type of information would show? I would need to know what types of fields go into an order/expenditure report so I could mock it up. - The Q&As indicated that the reports could consist of the following: Examples include, but are not limited to, the following: total expenditures by quarter and fiscal year, expenditures by category over a period of time, expenditures by vendor, license/product counts  by vendor, etc. And:  Examples of visualizations include, but are not limited to, the following: trends in orders by contract, trends in orders by department, trends in orders by product number, gross expenditures by contract, etc.

**Comment by ClaireReinken** [comment]
I believe this report should show over all sales with the ability to sort by contract, hardware, software, services, second tier categories of products (after first selecting a top tier like hardware), sales by quarter or fiscal year, or sales by department.

**Comment by davidatfei** [comment]
Drop-down to choose Product Type?
Checkboxes to drill down the specific products?
Product number or phone number entered in search box?

I don't understand how these apply to Overall Order Statistics. If they do, I need a very detailed description as to how they do and as to how these features should be implemented. My understanding was that the reports would be generated for a given date range and that we would only only include Shipped orders (I have included the ability to include Placed and UserCanceled as well.)

**Comment by ClaireReinken** [comment]
Hi David, I think this acceptance criteria may no longer apply. If you can turn the admin reports page into a dashboard, that would be great. If time runs out before code freeze, the current admin reports page looks good.

**Comment by davidatfei** [comment]
I updated the report page to include a Dashboard. The Dashboard replaces the filter page. The charts on the dashboard are abbreviated (less labeling) versions of the ones that display when expanded.

**Comment by jennymnh** [comment]
I made some minor style changes on the dashboard page (pulled the fields outside of the table).

**Comment by davidatfei** [comment]
After your changes, the form element on the page is unclosed and the Order Status select box is no longer multiselect.  I understand wanting to clean up the UI, but do we want to remove functionality to do it?

**Comment by davidatfei** [comment]
I also noticed that there is a Dashboard header that is showing for all of the reports. The dashboard is only one of the tabs available on that page. What was the reasoning behind labeling all of the different reports and raw data as Dashboard?

**Comment by jennymnh** [comment]
No we don't. I'll fix it once I come into the office.

Thanks.

**Comment by jennymnh** [comment]
Typically it's not the best UI practice  to put search options/filter/etc in a table since it is not tabular data. But given the time constraints I went ahead and just reverted my changes back to how it initially looked.
