### ISSUE TITLE
Authorized User Story 12 - Paging when browsing products

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#140]
As an authorized user, I want to be able to navigate through multiple pages of products so I can easily view and track my where I am in my search results.

Acceptance Criteria:
- When browsing products (either through search or by category), and there are many results:
- Total number of pages is displayed
- Page number that the user is currently on is displayed
- User can move forward one page if one exists
- User can move back one page if one exists
- User can jump to the last page of the results
- User can jump to the first page of the results

**Comment by davidatfei** [comment]
Please provide the URL or URLs for the page(s) where paging should be added.

**Comment by davidatfei** [comment]
Implemented paging on the product browse pages. The home page's Featured Products is not paged since it makes sense that "featured products" will not be a large list.

**Comment by neelusingh28** [comment]
Bug Details:
Tested in Chrome/Firefox/IE & devices:

Pagination is working as expected for categories but it is NOT available for quick search.

**Comment by ClaireReinken** [comment]
Writing separate issue for quick search.
