### ISSUE TITLE
Required fields for entering items to catalog

### ISSUE THREAD

**Issue by llin-freeman** [FEISystems/ca-adpq-prototype#141]
When entering or importing items to the catalog, please make the UNSPSC field not a required field.

**Comment by ClaireReinken** [comment]
Duplicate of Issue #150

**Comment by ClaireReinken** [comment]
Not duplicate

**Comment by davidatfei** [comment]
UNSPSC is no longer required

**Comment by lutech** [comment]
@neelusingh28 , I also added visual form validation to make it easier to know what is required.

**Comment by neelusingh28** [comment]
Browser: Chrome
logged in as Admin 1

1. Go to Add product> entered all fields except UNSPSC > Click on Add item > Add item does nothing.

**Comment by davidatfei** [comment]
Cannot reproduce. Works as expected. Please provide more detail if you are still having trouble.

**Comment by lutech** [comment]
Was able to reproduce. It has been resolved.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site and working as expected in Chrome, Firefox and IE.
