### ISSUE TITLE
Order History Page Clean Up

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#147]
Remove number of items . Please display information in a similar way as orders are displaying in "My Account". 

Include Order Number

Status currently shows as "0"; this needs to be changed to Pending OR Confirmed

**Comment by christianhfei** [comment]
This should all be ready for testing. The table is populating everything properly and the layout is good on all sizes.

https://github.com/FEISystems/ca-adpq-prototype/commit/db4a413266e13a22567fed965ae4a2b086cf9f20

**Comment by neelusingh28** [comment]
Please see this is still NOT fixed as per the requirements above other than status column. 

![image](https://cloud.githubusercontent.com/assets/25771656/23466785/0fe88540-fe6a-11e6-817e-68c5c47f0166.png)

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.
