### ISSUE TITLE
Cart Page Clean Up

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#149]
The cart is not currently displaying the unit price so it looks like when you order 5 items, the price that displays is for 1 item vs. 5. 

When the quantity selection is changed from a drop-down to a text field, the price should not update until the user clicks Update Cart. 

Remove the text box at the bottom of the page that contains help/call us info

**Comment by jennymnh** [comment]
~~@lutech , i was able to make all of the changes to this page except the price total. Could you look at that? Thanks.~~

Nevermind, I was able to figure it out. Moving to QC.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site and working as expected in Chrome, Firefox and devices.
