### ISSUE TITLE
Order Summary Page Clean Up

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#150]
- [x] Order Summary needs to show the unit price with subtotal and total for the entire order. 
- [x] Need validation check on all fields on this page. 
- [x] All fields should be required except Address 2 and 3. 
- [x] Reformat fields and condense if possible. 
- [x] Change "Address" label to "Shipped To Address"

**Comment by jennymnh** [comment]
Do we really want to change the label to "Shipped to Address"? If we do it makes it look like they need to enter three full addresses.

![image](https://cloud.githubusercontent.com/assets/9370407/23440211/bcd0e81a-fde8-11e6-9b8b-59e291dbe1c7.png)

**Comment by ClaireReinken** [comment]
Instead can we add the words "Ship to:" above the address lines?

- Claire Reinken

On Feb 28, 2017, at 7:04 PM, Jenny Ho <notifications@github.com<mailto:notifications@github.com>> wrote:


Do we really want to change the label to "Shipped to Address"? If we do it makes it look like they need to enter three full addresses.

[image]<https://cloud.githubusercontent.com/assets/9370407/23440211/bcd0e81a-fde8-11e6-9b8b-59e291dbe1c7.png>

-
