### ISSUE TITLE
Issue #117 Homepage Text is missing

### ISSUE THREAD

**Issue by neelusingh28** [FEISystems/ca-adpq-prototype#156]
1. Introductory text is missing on the homepage. 

2. When user clicks on logo then a square box appears - which it should not I guess. Please check screenshot. 

![image](https://cloud.githubusercontent.com/assets/25771656/23370482/d2972102-fce2-11e6-8e4d-6a023ca8776b.png)

**Comment by jennymnh** [comment]
@llin-freeman , does the "introductory text" mean the text from Kristie's mockups?

**Comment by llin-freeman** [comment]
Yes

I-Chun (Lisa) Lin-Freeman
Senior Associate

office   |  443.270.5100 x64858
direct   |  667.786.4858
fax       |  410.715.6538
email   |  Lisa.Lin-Freeman@feisystems.com<mailto:Lisa.Lin-Freeman@feisystems.com>

FEi Systems  |  9755 Patuxent Woods Drive, Suite 300 Columbia, MD 21046  |  www.FEIsystems.com<http://www.feisystems.com/>

This document may contain confidential and proprietary information of FEI.com, Inc. (FEi Systems). This information is intended for the use of the individual(s) or entity(s) to whom it is addressed. If you have received this email in error, please notify the sender immediately at the address shown and delete it from your files.

**Comment by jennymnh** [comment]
We still have one slideshow image with gears on it, are we putting text on it or should we remove it?

**Comment by jennymnh** [comment]
The image with the gears has text on it now. Ready for QC.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.
