### ISSUE TITLE
Internet explorer site issues

### ISSUE THREAD

**Issue by neelusingh28** [FEISystems/ca-adpq-prototype#157]
1. http://ca-adpq-docker1.fei.local:5000 - This link does not work in IE 11 - nothing comes up.
2. http://ca-adpq-docker1.fei.local:5001 - This link brings up only homepage after that none of the links works.

**Comment by neelusingh28** [comment]
Retested and found following issues:
1. http://ca-adpq-docker1.fei.local:5000 - Page comes up now but cart and compare list links not working. Once clicked site gets frozen and nothing else works. 
2. http://ca-adpq-docker1.fei.local:5001 - This link does not work in IE 11 - nothing comes up.

**Comment by JXPrime** [comment]
Found bug in compare list on dev and fixed. The stable site (5001) is updated periodically so it probably hasn't been refreshed yet.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.
