### ISSUE TITLE
Authorized User Story 1 - Quick Search

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#16]
As an authorized user, I want to quick search inventory by using keyword so I can quickly find item(s) I want.

Acceptance Criteria: 
•	User can enter keyword to search inventory
•	System allows user to use multiple keyword by separating them using “,”
•	System use entered key word(s) to search in following fields of items details:
o	Item Description
o	Category
o	Manufacturer 
o	Manufacturer Part Number (OEM #)
o	SKU#/Item#
•	System display search result (refer to search result user story)
* Search by exact words entered into the search field

**Comment by Mikewilburn302** [comment]
Questions:
1.	When searching by multiple keywords, is the system looking for results that have one or another, or does the system only look for products that have all?
2.	Is there a limit to how many characters can be accepted in the search bar?
3.	Is there a limit to how many keywords may be searched?
4.     If keywords are not separated by commas, will the system only search for match of the exact phrase? 
5.     Can we not search by item name?

Ideas:
1.	A dropdown of suggestions for commonly search items (similar to google and amazon)

**Comment by ClaireReinken** [comment]
Further Dev and UI tasks are recorded in Issues #80 and #81

**Comment by JXPrime** [comment]
@ClaireReinken can you address the questions @Mikewilburn302 posted above:

Questions:

When searching by multiple keywords, is the system looking for results that have one or another, or does the system only look for products that have all?
Is there a limit to how many characters can be accepted in the search bar?
Is there a limit to how many keywords may be searched?

**Comment by ClaireReinken** [comment]
When searching by multiple keywords, is the system looking for results that have one or another, or does the system only look for products that have all? one or another
 Is there a limit to how many characters can be accepted in the search bar? 25 characters
 Is there a limit to how many keywords may be searched? No
