### ISSUE TITLE
Issue #149 Cart Page issues

### ISSUE THREAD

**Issue by neelusingh28** [FEISystems/ca-adpq-prototype#161]
1. System is changing the price on changing the quantities however, system should change the price on clicking the 'update cart ' button
2. When '0' qty selected then total price is displaying as 'BLANK' it should display 0.00

**Comment by neelusingh28** [comment]
This is still not fixed

**Comment by JXPrime** [comment]
can you be more specific, there were multiple items on this ticket.

**Comment by neelusingh28** [comment]
Issue #2 is fixed but NOT 1. 

1. System is still changing the price on changing the quantities however, system should change the price on clicking the 'update cart ' button. if in case user clicks on the update cart button then 'update cart' and 'proceed to checkout' buttons are disappearing and there are items in the cart but system still displaying the message 'You have (0) items in your cart. Continue shopping.'  Please check the screenshot. 

![image](https://cloud.githubusercontent.com/assets/25771656/23481711/72c774c0-fe9a-11e6-96ca-0f851bff06b4.png)

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.
