### ISSUE TITLE
Error checking out

### ISSUE THREAD

**Issue by llin-freeman** [FEISystems/ca-adpq-prototype#162]
![error](https://cloud.githubusercontent.com/assets/22507715/23380794/2b91d7bc-fd0a-11e6-9562-c2f7f279b066.JPG)
Hi, I get a "Sorry, your order could not be processed at this time. Please try again. Go back to cart" error.  Any ideas?

**Comment by JXPrime** [comment]
Think I found the cause of this.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.

![image](https://cloud.githubusercontent.com/assets/25771656/23476417/b4cbc054-fe88-11e6-86c9-cfafb6955bfe.png)
