### ISSUE TITLE
http://ca-adpq-prototype.eastus2.cloudapp.azure.com/ - URL NOT WORKING IN IE

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#165]
It just shows a blank white page.

**Comment by llin-freeman** [comment]
In Chrome, the page loads, but the pictures do not
![missing pics](https://cloud.githubusercontent.com/assets/22507715/23409365/591cec64-fd99-11e6-94c9-64952af1967a.JPG)

**Comment by ClaireReinken** [comment]
URL now works on IE

**Comment by neelusingh28** [comment]
URL is working fine.
