### ISSUE TITLE
Issue #26 - Order History displays original price instead of discount

### ISSUE THREAD

**Issue by Mikewilburn302** [FEISystems/ca-adpq-prototype#166]
Browser: Chrome
User: AuthorizedUser1
Repro Steps:

1) Nav to My Account > Order History
2) Select Order to view
3) Verify that order displays original price

Description
Order history page displays each item's original price instead of contract discount price. The Total cost, however, is calculated from the discounted price. 

![2017-02-28_10-15-30](https://cloud.githubusercontent.com/assets/25773724/23410947/eb492b70-fd9e-11e6-91f8-9e47a59673e8.jpg)

**Comment by Mikewilburn302** [comment]
Order history is now totally blank

**Comment by JXPrime** [comment]
Couldn't reproduce on :5000 -
