### ISSUE TITLE
Issue #7 Admin Add Product issues

### ISSUE THREAD

**Issue by neelusingh28** [FEISystems/ca-adpq-prototype#169]
1. 'Cancel' button is NOT aligned to Add item
2. Select image file does not have an option to select any image
3. Despite all cells are filled - add item button remains inactive- are there any validation check on each cell's contents?
4. Please make sure user can preview the item content of the catalog before adding item. 

![Uploading image.png…]()

**Comment by ClaireReinken** [comment]
4.Please make sure user can preview the item content of the catalog before adding item. - Separate story

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site except #4.
