### ISSUE TITLE
Add "My Order History" link in top navigation

### ISSUE THREAD

**Issue by jennymnh** [FEISystems/ca-adpq-prototype#172]
Top navigation should also have the "My Order History" link.

**Comment by neelusingh28** [comment]
"My Order History" link is still not there on top navigation in 5000.

**Comment by jennymnh** [comment]
I currently have this link set to only appear when the user is logged in as an authorized user. Should I leave it like this? Or should the link always appear?

If it should only appear when a user is logged in, i'll have to hide it in the footer too. @ClaireReinken

**Comment by ClaireReinken** [comment]
The My Order History link should only appear when the user is logged in. Please hide it until the user logs in. Thank you.

**Comment by jennymnh** [comment]
Thanks. @neelusingh28 you can test this now. You will have to log in as an authorized user in order to see the links.

**Comment by neelusingh28** [comment]
@jennymnh 

The link is displaying as expected but if user logs out and logs back in with different user then clicking on My Order History link does not brings relevant results unless user clicks somewhere else on the site and then clicks again on My Order History link.

**Comment by jennymnh** [comment]
This has been fixed. I made it so when a user clicks "logout" it should take them back to the home page.

**Comment by neelusingh28** [comment]
My Order History link is working as expected in Chrome and in Firefox 

BUT

link is missing in devices Galaxy S5, ipad and iphone 6

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site and working as expected in Chrome, Firefox, IE and devices.
