### ISSUE TITLE
Order Confirmation page needs to mention an email confirmation being sent

### ISSUE THREAD

**Issue by jennymnh** [FEISystems/ca-adpq-prototype#173]
The order confirmation page needs to indicate that an email will be sent to the user. Need text from Lisa.

**Comment by llin-freeman** [comment]
How about this:
Thank you for shopping with us. A confirmation of this purchase will be sent by email. 
Your order number is XXXXX. To review all orders, visit your Order History.

**Comment by jennymnh** [comment]
This has been added, but we will need someone to add in the confirmation number (not sure if this has been implemented yet). @lutech  ?

**Comment by jennymnh** [comment]
It looks like someone else already changed the confirmation message to be an actual number. I am putting this in QC doing now.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.
