### ISSUE TITLE
Issue #17 Advance Search issues

### ISSUE THREAD

**Issue by neelusingh28** [FEISystems/ca-adpq-prototype#176]
1. If category is software then search bringing no results
2. As per data set spreadsheet Manufacturer drop down should have 6 line items but it displays only 2. - This is still not fixed. 
3. Category hardware brings only 10 results however, as per data set it should be 351

**Comment by davidatfei** [comment]
I added retrieval of the manufacturers and categories from the server to populate the drop downs. Note: the previously hard-coded values in the category box were actually Product Types. The box is not populated with categories, as the label suggests it should be.

**Comment by neelusingh28** [comment]
@lutech 

browser IE has issue:
Cells are sticking to each other and search and clear buttons should be horizontally right aligned. 

![image](https://cloud.githubusercontent.com/assets/25771656/23468742/9da6db2a-fe6f-11e6-9895-7743aa01cc4f.png)

**Comment by JXPrime** [comment]
I didn't notice this locally or on the 5000 site in IE, although it may have been fixed since this was opened.
![image](https://cloud.githubusercontent.com/assets/1841009/23476635/a2b13544-fe78-11e6-9393-2d030bda5b5b.png)

**Comment by christianhfei** [comment]
I just checked and I'm also not seeing anything breaking. @neelusingh28, can you please confirm if this is still an issue?

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.
