### ISSUE TITLE
Account Information Should display in the header

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#179]
When the user is logged in, the top bar navigation should state, "Hello, User Name" or something similar to indicate the user is logged in. We have no indication if you are logged in or out and that's causing issues.

**Comment by neelusingh28** [comment]
Logout suffixed with username is displayed in Chrome & Firefox but NOT in IE and devices (Galaxy S5, ipad and iphone 6)

**Comment by JXPrime** [comment]
can't repro. 
![image](https://cloud.githubusercontent.com/assets/1841009/23519033/bcb3fdf4-ff32-11e6-9096-a5a16850b31f.png)

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site and working as expected in Chrome, Firefox, IE and devices.
