### ISSUE TITLE
Authorized User Story 3 - Browse Inventory by Category

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#18]
As an Authorized User, I want to browse inventory by using category

Acceptance Criteria:
•	User can select a category to browse items
•	System display search result (refer to search result user story)

- [x] Add Category Pages to application.
     - Software
          - DDPE
          - Absolute Computrace
     - Hardware
          - Desktops
          - Laptops
          - Accessories
     - Services
          - Service Option Upgrades
              - By Device
          - Value Added Services
              - By Device
- [x] Display products/services using sample data.
- [x] Use Back end Services to display products/services using actual data.

**Comment by Mikewilburn302** [comment]
Questions:
1.	Are there any items that would be across multiple categories, like packages? If so, would they appear under all respective categories?
2.	Are there any sub-categories?
3.	Is there a default sort order when browsing by category?

**Comment by ClaireReinken** [comment]
Questions:
1.Are there any items that would be across multiple categories, like packages? If so, would they appear under all respective categories? - No such package is included in the Prototype A resources. An item should only be able to appear under one category at this time. 
2.Are there any sub-categories? - Yes, the top tier should be Hardware, Software, Services and the user should be able to drill-down on a set number of sub categories. 
3.Is there a default sort order when browsing by category? - Yes, I think we should order the products by anticipate popularity, such as Laptop and Desktops before say Computer Memory.

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues #84 and #85

**Comment by Mikewilburn302** [comment]
Need items in all 3 categories to test
