### ISSUE TITLE
View details by clicking on the picture

### ISSUE THREAD

**Issue by llin-freeman** [FEISystems/ca-adpq-prototype#180]
User input we received re: expected usability-- Could clicking on the product image behave like clicking on the "view details"?  This makes it easier to view the product details.

**Comment by JXPrime** [comment]
Addressed in https://github.com/FEISystems/ca-adpq-prototype/commit/3434d7ab14706b0bb594f6614407e55cc4018a15

**Comment by JXPrime** [comment]
@llin-freeman I don't see this on the board (the projects on the right is blank?) but it's ready to be tested in 5000

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.
