### ISSUE TITLE
Issue #23 - Email not being saved when clicking Continue

### ISSUE THREAD

**Issue by Mikewilburn302** [FEISystems/ca-adpq-prototype#181]
Browser: Chrome (only in Chrome)
User: AuthorizedUser1

Reprosteps
1) Add items to cart
2) Checkout
3) Enter all info and email
4) Click Continue
5) Validate email is now blank

Email is not saved in chrome when clicking continue.

**Comment by JXPrime** [comment]
Couldn't reproduce locally.

**Comment by Mikewilburn302** [comment]
Working now
