### ISSUE TITLE
Issue #22 System is NOT validating phone number and zip code in checkout information

### ISSUE THREAD

**Issue by neelusingh28** [FEISystems/ca-adpq-prototype#187]
Add items to the cart>go to the cart>Click on proceed checkout >enter alphabetic text in phone number and zip code instead of numeric. System allows to proceed.

System should validate 10 digit phone number and 5 digit zipcode

**Comment by jennymnh** [comment]
The issue has been resolved. Moving to QC

**Comment by Mikewilburn302** [comment]
System still allowing text in numeric fields

**Comment by jennymnh** [comment]
This is currently working for me. I'm able to enter text into the textbox, but the field validation will appear and prevent you from continuing.
Here's how it's looking on my :5000 site, does it have a similar appearance for you?
![image](https://cloud.githubusercontent.com/assets/9370407/23527034/4c24e2c6-ff62-11e6-97a2-af59dcc41878.png)

updated my screenshot with the full screen
![image](https://cloud.githubusercontent.com/assets/9370407/23527057/6835fe5a-ff62-11e6-88f4-ea3dbe0dffca.png)

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site and working as expected in Chrome, Firefox, IE and devices.
