### ISSUE TITLE
Authorized User Story 4 - View Search Results

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#19]
As an Authorized User, I want to view the search result in a list page

Acceptance Criteria:
•	Display following columns
o	Item Picture
o	Item Description
o	Category
o	Manufacturer
o	Manufacturer Part Number (OEM #)
o	SKU#/Item#
o	Price
o	Availability
•	User can sort by:
o	Name
o	Item Description
o	Category
o	Manufacturer
o	Manufacturer Part Number (OEM #)
o	SKU#/Item#
o	Price
o	Availability
•	Each item  have a check box for user to select the item for comparison to add it to shopping cart

**Comment by Mikewilburn302** [comment]
Questions:
1.	Are there pictures for services and warranties?
2.	What exactly is the item description? How long is it? Is it a few words, a paragraph?
3.	What is the default order?
4.	If sorting by Item description, is it alphabetical by the first word in the description? 
5.	What are the tiers of sorting? Let’s say I sort by Availability and it shows me “In Stock” items first. How are those In Stock items sorted? 
6.     How many results per page?




Ideas:
1.	Sorting by Relevance
a.	If I search via multiple keywords, I’d like to see items that have all keywords first, then items that have some words, then items that have one word.

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues #86 and #87

**Comment by neelusingh28** [comment]
Testing cannot be proceeded further. Showstopper. Bug created #159

**Comment by JXPrime** [comment]
#159 was addressed cc: @neelusingh28

**Comment by neelusingh28** [comment]
@ClaireReinken 

Q1. Quick Search is working now but its is NOT displaying the products with following columns as per the acceptance criteria. Is it expected?

Q2. There is no option to sort the products. Is it expected?

Please checkout the screenshot of quick search

![image](https://cloud.githubusercontent.com/assets/25771656/23414852/4d4ca584-fdab-11e6-88b5-c9462429a1a9.png)

**Comment by ClaireReinken** [comment]
Q1. Quick Search is working now but its is NOT displaying the products with following columns as per the acceptance criteria. Is it expected? - That's fine

Q2. There is no option to sort the products. Is it expected? - Yes, I think this can be closed.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.
