### ISSUE TITLE
ISSUE #114 - User cannot filter Trends by Dept.

### ISSUE THREAD

**Issue by Mikewilburn302** [FEISystems/ca-adpq-prototype#194]
Browser: Chrome
User: Admin1
Repro Steps

Log in as Admin1
Go to Admin homepage
Set report data to 1/1/2015-3/31/2017
Expand Trends report
Validate user cannot filter

There is no option to filter trends by department

**Comment by davidatfei** [comment]
Please review, Claire. I don't think we plan to add this.

**Comment by ClaireReinken** [comment]
Let's just show all departments at this point.
