### ISSUE TITLE
 When I restart a session, it still shows me as logged in but I cannot see Admin or My Order History

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#199]
I think this is a bug

**Comment by ClaireReinken** [comment]
[‎3/‎3/‎2017 10:15 AM] Claire Reinken: 
So when I was looking at the site the other day, it said "Logout (Admin2)" at the top but I was unable to add things to cart
I clicked on Logout and then the login appeared and I wasn't logged in anymore but it still showed "logout"
This was after I stopped a session and then resumes
*resumed it
Does that help?
[‎3/‎3/‎2017 10:22 AM] Terry Boswell: 
when you say stopped a session then resumed, what do you mean?
[‎3/‎3/‎2017 10:22 AM] Claire Reinken: 
I closed IE and then went back to the page

**Comment by neelusingh28** [comment]
I observed a slightly different issue now...in chrome/Firefox and IE

1. Log in as Admin1 - System displays as expected Logout (Admin 1) and Admin & My Order History on top left
2. Close the browser
3. System displays the site with Logout (Admin 1) but Admin & My Order History on top left **disappears**
4. System allows to perform any other actions like add to cart, compare and place order

@ClaireReinken - I guess we need to know correct expected results that what should happen if in case user close the browser and restarts.

**Comment by ClaireReinken** [comment]
Expected results should be:

- When a user is logged in, the system should display Logout(User Name)

- When the user is logged out, the system should display Login

**Comment by neelusingh28** [comment]
@ClaireReinken - Above expected results are working fine if user manually clicks on logout . Can we know the expected results for closing the browser without manually logging out?

**Comment by ClaireReinken** [comment]
If the user closes the browser, they should be logged out.

**Comment by neelusingh28** [comment]
I have retested, closing the browser is NOT logging out the user. Below are the bug details.

1. Log in as Admin1 - System displays as expected Logout (Admin 1) and Admin & My Order History on top left
2. Close the browser
3. System displays the site with Logout (Admin 1) but Admin & My Order History on top left disappears
4. System allows to perform any other actions like add to cart, compare and place order

**Comment by JXPrime** [comment]
That's not how it works. We issue a cookie which lasts for a day. Even if you close your browser the cookie will remain.

**Comment by neelusingh28** [comment]
All right closing then since manual log out is working fine.
