### ISSUE TITLE
Authorized User Story 5 - Compare Items

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#20]
As an Authorized User, I want to select certain items for comparison so I can decide which one would be the best choice

Acceptance Criteria:
•	User can choose up to 4 items to compare from the search result page
•	System display following info in comparison page in a table:
o	Item picture
o	Item Description
o	Category
o	Manufacturer
o	Manufacturer Part Number (OEM #)
o	SKU#/Item#
o	Price
•	User should able to add one or multiple items to shopping cart from comparison page
* Users should be able to add items to their cart from the compare page

**Comment by Mikewilburn302** [comment]
Questions:
1.	No Name field in comparison?
2.	Can a user remove items from comparison table?
3.	What happens if the user tries to select a fifth item? Is there an error message?

**Comment by ClaireReinken** [comment]
Questions:
1.No Name field in comparison? - Agreed, this field should be added. 
2.Can a user remove items from comparison table? Yes, a user should be able to remove items from the comparison table. 
3.What happens if the user tries to select a fifth item? Is there an error message? Yes

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues #88 and #89

**Comment by Mikewilburn302** [comment]
Bug details

1) Cannot remove items. When clicking remove, compare list is closed. If it is reopened, the removed item is still present. It should simply remove the item without closing the compare list

2) Add fields: SKU, OEM, Item Name, Category

3) Remove fields: MSRP and Discount percentage

Impediment

1) Need more than 4 items in inventory to validate no more than four items can be added to compare list

**Comment by lutech** [comment]
Issues have been resolved. Few notes, OEM is the same as Manufacturer. I have renamed to OEM.  Based on Hatem's feedback, I have kept MSRP and Discount percentage to show incentive to users. Products DB should now fully be accessible for testing.

**Comment by Mikewilburn302** [comment]
SKU# is missing from compare list

**Comment by JXPrime** [comment]
Added SKU to compare list (make sure to clear your local browser cache) cc: @Mikewilburn302
