### ISSUE TITLE
When more than 4 items added for compare then Clear All link in pop up does not clear items selected

### ISSUE THREAD

**Issue by neelusingh28** [FEISystems/ca-adpq-prototype#203]
Browser Chrome:

Check more than 4 items for compare>System will display pop up on the top with Clear All link> click on that link>nothing happens

I think the expectation is that system should uncheck all the items selected for compare.

![image](https://cloud.githubusercontent.com/assets/25771656/23556261/fa37fd48-fff9-11e6-96b9-ba6a0e1653c1.png)

**Comment by JXPrime** [comment]
The "clear all" functionality I was unable to make function. I removed that text from the message.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site and working as expected in Chrome, Firefox, IE and devices.
