### ISSUE TITLE
Authorized User Story 6 - Browse Item Details

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#21]
As an Authorized User, I want select an item to view so I can browse the details
Acceptance Criteria:
•	Following information displayed in details page:
o	Item picture
o	Item Description
o	Category
o	Manufacturer
o	Manufacturer Part Number (OEM #)
o	SKU#/Item#
* Discount Price
•	User have “Add to Cart” option
•	User can modify quantity to “Add to Cart”, default is 1
•	User have option to view enlarged version of item picture

**Comment by Mikewilburn302** [comment]
Questions:
1.	What does the user click to open the item? The picture? The name?
2.	Are we displaying any additional add-ons in any way?
3.	What about product specs? For example, for PCs we could display the CPU, GPU, RAM, Mem, Mobo, Power Supply, etc.
4.	Do any items have variables, like color, size? If so, can that be chosen in item details when adding to cart?

Ideas:
1.	Display similar items or suggested items
2.	Display product reviews

**Comment by ClaireReinken** [comment]
Questions:
1.What does the user click to open the item? The picture? The name? - The user should be able to click the more details button to see the expanded view of the item. The name and picture should also allow the user to open the item. 
2.Are we displaying any additional add-ons in any way? Targeted for Sprint 2, not for Sprint 1. See Issue #31 
3.What about product specs? For example, for PCs we could display the CPU, GPU, RAM, Mem, Mobo, Power Supply, etc. - The product specs will only match the data provided in the Prototype A Resources PDF
4.Do any items have variables, like color, size? If so, can that be chosen in item details when adding to cart? - No. 

Ideas:
1.Display similar items or suggested items - Targeted for Sprint 3 - See Issue #38 
2.Display product reviews - I will request a user story for Sprint 3 for this. See Issue #69

**Comment by jennymnh** [comment]
In terms of pictures, how are we going to procure them? Given how long the product list is it may be difficult and not the best use of time to find the exact pictures for every single item.

Should we do a few and show a "no image" placeholder image for the rest?

**Comment by ClaireReinken** [comment]
In terms of pictures, how are we going to procure them? Given how long the product list is it may be difficult and not the best use of time to find the exact pictures for every single item. - For the purposes of the prototype, we will use one stock image for every second tier product category. For example, every laptop will show the same laptop image. Luis can provide the images. 

Should we do a few and show a "no image" placeholder image for the rest? Please use a no image placeholder for any items that do no lend themselves to images such as warranties or certain services.

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues  #90 and #91

**Comment by ClaireReinken** [comment]
We will not show the discount percentage or the list price, only the Discount Price, when viewing the item details. While this information will still be entered by the admin user, we feel only the final price is useful to the authorized user and will prevent confusion.

**Comment by neelusingh28** [comment]
Bug Details:

1. Pictures are still NOT available. So cannot test enlarge picture either.
2. CLIN, Contractor, Contractor# and Contract Expiration Date has been added additionally. Is that expected?
3. Contract Expiration Date: 2017-06-10T00:00:00 displaying like this, I guess time stamp not needed

**Comment by ClaireReinken** [comment]
1.Pictures are still NOT available. So cannot test enlarge picture either. - Pictures should be added now. 
2.CLIN, Contractor, Contractor# and Contract Expiration Date has been added additionally. Is that expected? - That's fine, let's keep it. 
3.Contract Expiration Date: 2017-06-10T00:00:00 displaying like this, I guess time stamp not needed - Time stamp is not needed. This should be a bug.

**Comment by JXPrime** [comment]
Changed format of contract expiration date. cc: @neelusingh28

**Comment by neelusingh28** [comment]
Enlarge view of pictures is still NOT available.

**Comment by jennymnh** [comment]
I think the original plan was to have three additional images that the user could click on to view, but since that didn't happen I don't think we need an enlarged view anymore. The images for the products right now are the largest version (I think). 

I would not try to implement this feature. Any thoughts? @ClaireReinken

**Comment by ClaireReinken** [comment]
I think the original plan was to have three additional images that the user could click on to view, but since that didn't happen I don't think we need an enlarged view anymore. The images for the products right now are the largest version (I think).

I would not try to implement this feature. Any thoughts? @ClaireReinken

- Agreed. Let's remove this feature. If all other items are addressed, we can close this one.

**Comment by lutech** [comment]
@ClaireReinken , @neelusingh28  I'm not sure what actions need to take place here if any. Can you please clarify?

**Comment by ClaireReinken** [comment]
No action needed
