### ISSUE TITLE
Authorized User Story 8 - Place an Order

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#23]
As an Authorized User, I want to place an order 

Acceptance Criteria:
•	User have “check out” option from shopping cart
•	User enter required information for checkout (I’m not sure what exact information would be required in this case, I just listed some examples)
o	Name
o	Department
o	Phone Number
o	Email Address
o	Delivery Address
o	Payment Method (State Agency Account Number): drop-down of four different built-in account numbers from four different agencies.

•	System compile order info and asks user to review
* Need to be able to update the cart to edit quantities
•	User can cancel or confirm the order and system will generate order # if user confirmed
* Need to be able to edit information throughout check out procedure using quick links to change payment account and address information
* Need to be able to "cancel and continue shopping" from the place your order page
* Need to be able to return to the cart of continue shopping during each step of the check out procedure

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues #94 and #95

**Comment by ClaireReinken** [comment]
For the purposes of this prototype, we will not manage adding payment information at this time. Four different departmental accounts will be added as a payment method and the authorized user can select from one of the four accounts.

**Comment by ClaireReinken** [comment]
Lisa, can you please provide the names of the four departments that will be associated with each payment account?

**Comment by llin-freeman** [comment]
Let's go with:
1-California Department of General Services
2- California Department of Technology
2-California Department of Health and Human Services
3-California Department of Education

**Comment by ClaireReinken** [comment]
For the purposes of this prototype, we will not calculate sales tax.

**Comment by Mikewilburn302** [comment]
Bug Details:
1) Why is address one line? Are we not doing Address 1, Address 2, City, State, Zip?

2) Clicking "Continue" does nothing

3) Clicking "Back to Cart" does nothing

**Comment by lutech** [comment]
@JXPrime  @ClaireReinken , I know we discussed what we should be capturing for orders today, just want to confirm if Departments and Phone Number are still part of the requirements. Currently I have it in the UI but I don't think the back end supports them.

**Comment by ClaireReinken** [comment]
Let's keep the phone number but we won't store it. We can remove the department because that will be associated at payment.

- Claire Reinken

On Feb 23, 2017, at 11:52 PM, lutech <notifications@github.com<mailto:notifications@github.com>> wrote:


@JXPrime<https://github.com/JXPrime> @ClaireReinken<https://github.com/ClaireReinken> , I know we discussed what we should be capturing for orders today, just want to confirm if Departments and Phone Number are still part of the requirements. Currently I have it in the UI but I don't think the back end supports them.

-

**Comment by JXPrime** [comment]
@lutech I missed phone number when I was adding the other address fields...also the intent for the State field was for it to be a dropdown, but I don't think there is a lookup for that yet.

**Comment by lutech** [comment]
@JXPrime  Thanks. I omitted phone number and department for now. Also, no need for state lookups. I made the change on the front end, its now a drop down. Latest check-ins should reflect this.

**Comment by lutech** [comment]
@JXPrime Hey Jonas, can you please take a look at the service. It doesn't seem to be working even in swagger.

**Comment by JXPrime** [comment]
I found an issue related to the shopping cart that was preventing orders from going through, I've fixed that and will move this back to QC doing.

**Comment by llin-freeman** [comment]
Thank you!

I-Chun (Lisa) Lin-Freeman
Senior Associate

office   |  443.270.5100 x64858
direct   |  667.786.4858
fax       |  410.715.6538
email   |  Lisa.Lin-Freeman@feisystems.com<mailto:Lisa.Lin-Freeman@feisystems.com>

FEi Systems  |  9755 Patuxent Woods Drive, Suite 300 Columbia, MD 21046  |  www.FEIsystems.com<http://www.feisystems.com/>

This document may contain confidential and proprietary information of FEI.com, Inc. (FEi Systems). This information is intended for the use of the individual(s) or entity(s) to whom it is addressed. If you have received this email in error, please notify the sender immediately at the address shown and delete it from your files.
