### ISSUE TITLE
Authorized User Story 9 - View Order Details

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#24]
As an Authorized User, I want to select an order to view so I can see the order details

Acceptance Criteria:
•	System display following info in order details page:
o	Order Date
o	Order #
* Email Address
o	Order placed by (Name/Department)
o	Delivery Address
o	Status 
o	Item list:
Product Name
	Item description
	Quantity
	Price
	Item total
o	Order Total
•	User should able to cancel the order from details page

**Comment by neelusingh28** [comment]
I think tracking number should not be there at this point of time in the prototype.
Product Name can also be added in the item list.

**Comment by ClaireReinken** [comment]
I think tracking number should not be there at this point of time in the prototype.
 Product Name can also be added in the item list. Agreed. since we removed shipping, we should not have a field for tracking number. I will delete it from the user story.

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues #96 and #97
