### ISSUE TITLE
Authorized User Story 11 - View Order History

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#26]
As an Authorized User, I want view order history to I see a list or orders I placed
Acceptance Criteria:
•	User can use “My Orders” function to track order status
•	User can view a list of orders with following columns
o	Order Date
o	Order #
o	Order Total
o	Order Status
	Pending
	Confirmed
	Cancelled
•	User can select an order to view details from history page
•	User can select an order to cancel from history page

**Comment by neelusingh28** [comment]
Q1. Can user first see list of orders placed during certain time frame yearly wise and then click on order details to know further details? 
Q2. Can a user also see following information:
List of no items ordered
Price (original, discounted or both)
billing address
shipping address
Payment method
Track Shipment info
Q3. Can user view or print invoice? 
Q4. Will there be an option to write a product review? 
Q5. Can an order be searched? 
Q6. Will orders be categorized as Orders, open orders and cancelled orders? orders by date ordered and then show status that indicates if it’s open, ordered, or cancelled

**Comment by ClaireReinken** [comment]
See below.

Claire Reinken, AM.PMP
Senior Proposal Manager

office   | 443.472.4613
fax       | 410.715.6538
email   |  claire.reinken@FEIsystems.com<mailto:claire.reinken@FEIsystems.com>
FEi Systems
9755 Patuxent Woods Drive, Suite 300 Columbia, MD 21046 |  www.FEIsystems.com<http://www.feisystems.com/>

**Comment by neelusingh28** [comment]
Thanks for the answers above. few more -
Q7. Will it have an option of buy it again?
Q8. If any item is returned then can return/refund status be viewed?

**Comment by ClaireReinken** [comment]
See below

Claire Reinken, AM.PMP
Senior Proposal Manager

office   | 443.472.4613
fax       | 410.715.6538
email   |  claire.reinken@FEIsystems.com<mailto:claire.reinken@FEIsystems.com>
FEi Systems
9755 Patuxent Woods Drive, Suite 300 Columbia, MD 21046 |  www.FEIsystems.com<http://www.feisystems.com/>

**Comment by neelusingh28** [comment]
If no orders placed in past , I'm expecting system will display message something like "you have not placed any orders in past"?

**Comment by tzhangfei** [comment]
If no orders placed in past , I'm expecting system will display message something like "you have not placed any orders in past"? **Yes**

**Comment by ClaireReinken** [comment]
If no orders placed in past , I'm expecting system will display message something like "you have not placed any orders in past"? Yes

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues #100 and #101
