### ISSUE TITLE
Admin User Story 3 - Bulk Import Catalog Items

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#27]
As an administrator, I want to add product catalog items in bulk so that each item does not have to be added line by line or cell by cell

Acceptance Criteria:
•	Administrators can import the catalog in .xlsx or .CSV format by using a bulk feature to import all items at once
•	The spreadsheet must contain the following data columns: 
o	CLIN
o	UNPSC Code (Version 11)
o	Manufacturer Part Number (OEM #)
o	Manufacturer (OEM)
o	SKU #/ Item #
o	Item Name 
o	Item Description
o	Unit of Measure
o	List Price/MSRP
o	Contract Unit Price
o	Contract Discount
o	Category 
o	Product Type
o	Contract #
o	Contract Vendor
o	Contract Expiration Date
o	Product Image URL
•	The import feature will automatically not import any records duplicated in the spreadsheet or records already in the system

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues #108 and #109

**Comment by davidatfei** [comment]
This feature has been implemented and is testable.  However, it was implemented using the db schema from early in the week.  Changes are required to include schema changes that were made during the week.

**Comment by Mikewilburn302** [comment]
Is there any check in case an admin uploads the same file twice? How do we prevent duplicate items?

**Comment by ClaireReinken** [comment]
Is there any check in case an admin uploads the same file twice? How do we prevent duplicate items? - Yes, we will use the CLIN number and contract number to identify a catalog item as an unique item. When a user attempts to upload duplicate items, an error will appear to the user, "X number of items successfully uploaded, X items failed to upload because they are already in the catalog." Or similar wording. If possible, we should tell the user what item failed to upload.

**Comment by ClaireReinken** [comment]
The Admin user would have to enter the product image column information. We’ll have instructions on the import page that indicates to show product images, this column need to contain a path to the image in their repository.

**Comment by Mikewilburn302** [comment]
Can I be sent an email containing a csv inventory file I could use?

**Comment by llin-freeman** [comment]
Hi Luis,
Can you send Mike the data file?

Thanks,
Lisa


I-Chun (Lisa) Lin-Freeman
Senior Associate

office   |  443.270.5100 x64858
direct   |  667.786.4858
fax       |  410.715.6538
email   |  Lisa.Lin-Freeman@feisystems.com<mailto:Lisa.Lin-Freeman@feisystems.com>

FEi Systems  |  9755 Patuxent Woods Drive, Suite 300 Columbia, MD 21046  |  www.FEIsystems.com<http://www.feisystems.com/>

This document may contain confidential and proprietary information of FEI.com, Inc. (FEi Systems). This information is intended for the use of the individual(s) or entity(s) to whom it is addressed. If you have received this email in error, please notify the sender immediately at the address shown and delete it from your files.

**Comment by davidatfei** [comment]
Mike, open git board. Go to the code tab. Choose the develop branch.

ca-adpq-prototype/ca_proto/ca_service/DbScripts/

There are images in a folder there and there is a csv there: Data Set_ADPQ_v5.csv is the one to use.

**Comment by Mikewilburn302** [comment]
I need a csv file that has not already been uploaded. Everything is skipped because they are duplicates
