### ISSUE TITLE
User Accounts for Authorized Consumer and Admin Users

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#28]
The Prototype should have 3 authorized consumer user accounts and 2 admin user accounts with login information. 

Acceptance criteria:
Following Admin accounts are created:
**Admin Account 1:**
 - Username: Admin1
 - Password: @dMin1

**Admin Account 2:**
 - Username: Admin2
 - Password: @dMin2

Following Consumer account are created:
**Authorized User Account 1:**
 - Username: AuthorizedUser1
 - Password: AuthorizedU$er1

**Authorized User Account 2:**
 - Username: AuthorizedUser2
 - Password: AuthorizedU$er2

**Authorized User Account 3:**
 - Username: AuthorizedUser3
 - Password: AuthorizedU$er3

**Comment by TerryBoswell** [comment]
API Calls are now built out. There is an authenticate method, create user method. There sql script to create the data is called CreateUserTable.txt. AdministratorFilter and AuthenticationFilter for securing api endpoints. The authentication filter is used for any endpoints that require authentication but does not require administrator access. The administratorfilter is used to secure api endpoints only accessible to admins

**Comment by TerryBoswell** [comment]
I believe that you have a typeo 
Username: AuthorizedUser1
Password: **AuthorizedU$er2**
