### ISSUE TITLE
Build CI/CD environment

### ISSUE THREAD

**Issue by jtanus** [FEISystems/ca-adpq-prototype#3]

**Comment by ryan-chadwick-fei** [comment]
I'll be breaking this one down into child issues

Process goes a little something like this:

1.	AppVeyor project gets linked to the GitHub project via one of their sweet web hooks
2.	GitHub sends information on each push over the web hook to AppVeyor
a.	This gets limited to specific branches (in our case Dev and stable/web/b)
3.	This triggers AppVeyor to clone that branch from your repository
a.	Only the branch that is noted in the push and only if that branch is targeted in the AppVeyor settings
4.	AppVeyor looks for an parses the appveyor.yml which contains build instructions and configurations
5.	Appveyor.yml tells PS build script to run which does all the dotnet restore/test/build/publish stuff
6.	Appveyoy.yml tells the engine to run git commands to checkout/commit/push to a release branch
a.	Pushes to latest/web/r if built from Dev
b.	Pushed to stable/web/r if build from stable/web/b
7.	Docker Hub get linked to GitHub project via one of their sweet web hooks
8.	Docker Hub auo-build can trigger Dockerfile image builds in its cloud service on a push from the web hook
a.	Dockerfile is built and Docker image is tagged latest if built from latest/web/r
b.	Dockerfile is built and Docker image is tagged stable if built from stable/web/r
9.	Centurylink/watchtower is a Docker image that monitors local docker containers and their remote repositories on Docker Hub
10.	Watchtower sees the auto-build of the Docker image complete and pulls it down
11.	Watchtower stops, updates, and starts the container using that tagged image

Some fun links below.  You can check out the appveyor.yml, PS build script, and Dockerfile in our GitHub repo.  The last link is what I used as a starting point.

https://www.appveyor.com/docs/

https://docs.docker.com/docker-hub/builds/

https://hub.docker.com/r/centurylink/watchtower/
