### ISSUE TITLE
Authorized User Story 13 - Catalog Item Names Need to be Shortened from Provided Descriptions

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#30]
Many of the hardware descriptions provided in the Prototype A resources can be a paragraph long. The item titles should be shortened to the first few key words with the full description appearing in item details.

**Comment by neelusingh28** [comment]
We should make sure to continue to use the same keywords for all those hardware items across all users stories. I guess we would be using the same keywords for searching an browsing the item too.

**Comment by ClaireReinken** [comment]
Agreed, I suggest we add a column to the data set with the shortened titles so they are consistent.

Claire Reinken, AM.PMP
Senior Proposal Manager

office   | 443.472.4613
fax       | 410.715.6538
email   |  claire.reinken@FEIsystems.com<mailto:claire.reinken@FEIsystems.com>
FEi Systems
9755 Patuxent Woods Drive, Suite 300 Columbia, MD 21046 |  www.FEIsystems.com<http://www.feisystems.com/>

**Comment by llin-freeman** [comment]
Added new column to the  data--"product title"--with shortened name.
