### ISSUE TITLE
Complied with Section 508 of the Americans with Disabilities Act and WCAG 2.0;

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#48]
Complied with Section 508 of the Americans with Disabilities Act and WCAG 2.0;

- [x] Test accessibility of site 

- [x] Verify all resolved accessibility issues

**Comment by kcallander** [comment]
I have rechecked everything with the WAVE tool and looks good... zero errors. Assigning to Roman so he can check with the JAWS reader.

**Comment by ClaireReinken** [comment]
To ensure compliance without incurring refactoring costs, our team weaves Section 508 requirements into design, development, and testing at the beginning of every project. FEi also carefully considered the design of the prototype to ensure 508 compliance up to WCAG AA level through utilizing the following guidelines and technology: 
	W3C accessibility recommendations
	WAI-ARIA (technology that makes advanced web applications accessible and usable to people with disabilities)
	Americans with Disabilities Act (ADA) laws and regulations
	Web Content Accessibility Guidelines (WCAG) 2.0
	Principles of Accessibility: Perceivable, Operable, Understandable, Robust (POUR)
	Assistive technology (e.g., screen readers, magnification, assistive listening devices)
	Text, graphics, images, menus, breadcrumbs, forms, navigation, buttons, tables, accessibility tags, fonts, plugins, links, scripts, and applets
	Code and markup that define page structure and presentation
	Evaluation with web accessibility checkers, HTML and WCAG evaluators, and CSS validators
	HTML elements (name, role, state, value)
	HTML markup that conveys logical hierarchy
	HTML tables (data, complex, simple, layout)
	Proper header, cell, row, and column associations
	Tables constructed to read logically from left to right and top to bottom
	Tables containing attributes to define meaning in the absence of context
	Layout, color, contrast, and cascading style sheets (CSS), including the disabling of CSS during testing
	Form fields (FIELDSET, LEGEND, TABINDEX), radio buttons, checkboxes, labels (with FOR attribute), title attribute, order
	Keyboard accessibility
	Logical tab order
	Accessible links
	Forms that can be navigated and completed
	Content that is accessible when displayed on hover
	Visual focus that moves with keyboard navigation

The prototype was tested using the WAVE web accessibility tool and JAWS 16 screen reader. During initial testing, there were some errors that showed up when using WAVE as well as doing keyboard navigation and selection.
