### ISSUE TITLE
Created or used a design style guide and/or a pattern library

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#49]
Created or used a design style guide and/or a pattern library 
Digital Play 3: Make it simple and intuitive
* Use a simple and flexible design style guide for the service. Use the U.S. Web Design Standards as a default
* Use the design style guide consistently for related digital services
* Give users clear information about where they are in each step of the process
* Follow accessibility best practices to ensure all people can use the service
* Provide users with a way to exit and return later to complete the process
* Use language that is familiar to the user and easy to understand
* Use language and design consistently throughout the service, including online and offline touch points

**Comment by lutech** [comment]
For the UI style guide, we are following the guidelines specified in the U.S. Web Design Standards specification found at https://standards.usa.gov/.
