### ISSUE TITLE
Created a prototype that works on multiple devices, and presents a responsive design

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#52]
Created a prototype that works on multiple devices, and presents a responsive design

**Comment by neelusingh28** [comment]
Below Navigation is missing on devices. Tested on mobile emulator for Galaxy S5 and iphone 6 plus and ipad

![image](https://cloud.githubusercontent.com/assets/25771656/23439922/0fb2e026-fde7-11e6-94b9-68b9ef341914.png)

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site.
