### ISSUE TITLE
Used at least 5 modern and open-source technologies, regardless of architectural layer

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#53]
Used at least five (5) modern and open-source technologies, regardless of architectural 
layer (frontend, backend, etc.). " Modern” is to be understood as any technology or standard released, created, initiated or finalized in the five (5) years preceding the release of this RFI.
Digital Play 8: Choose a modern technology stack
* Choose software frameworks that are commonly used by private-sector companies creating similar services
* Whenever possible, ensure that software can be deployed on a variety of commodity hardware types
* Ensure that each project has clear, understandable instructions for setting up a local development environment, and that team members can be quickly added or removed from projects
* Consider open source software solutions at every layer of the stack
Digital Play 13: Default to open
* Offer users a mechanism to report bugs and issues, and be responsive to these reports
* Provide datasets to the public, in their entirety, through bulk downloads and APIs (application programming interfaces)
* Ensure that data from the service is explicitly in the public domain, and that rights are waived globally via an international public domain dedication, such as the “Creative Commons Zero” waiver
* Catalog data in the agency’s enterprise data inventory and add any public datasets to the agency’s public data listing
* Ensure that we maintain the rights to all data developed by third parties in a manner that is releasable and reusable at no cost to the public
* Ensure that we maintain contractual rights to all custom software developed by third parties in a manner that is publishable and reusable at no cost
* When appropriate, create an API for third parties and internal users to interact with the service directly
* When appropriate, publish source code of projects or components online
* When appropriate, share your development process and progress publicly

**Comment by TerryBoswell** [comment]
Our technology stack is a service oriented .Net Core server solution with a single page component based application

1. Asp.Net Core
2. MySQL
3. Swashbuckle Swagger
4. AngularJS 1.5
5. MySQL Connector https://github.com/mysql-net/MySqlConnector
6. X-Unit for server side testing
