### ISSUE TITLE
Deployed the prototype on an Infrastructure as a Service (IaaS) or PaaS provider

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#54]
Deployed the prototype on an Infrastructure as a Service (IaaS) or Platform as Service (PaaS) provider, and indicated which provider they used

**Comment by ryan-chadwick-fei** [comment]
Acquired Azure resources from IT
will proceed with migrating to Azure in Sprint 3
Will leave existing internal QC servers operating along side

**Comment by ryan-chadwick-fei** [comment]
This is a parent issue to
[Implement Elastic Hosting Layer in Azure #77](https://github.com/FEISystems/ca-adpq-prototype/issues/77)
[Implement Elastic Application Layer in Docker Swarm #137](https://github.com/FEISystems/ca-adpq-prototype/issues/137)
[Implement Docker Swarm #74](https://github.com/FEISystems/ca-adpq-prototype/issues/74)

**Comment by ryan-chadwick-fei** [comment]
Production site is running in Azure
