### ISSUE TITLE
Developed automated unit tests for their code

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#55]
Developed automated unit tests for their code
Digital Play 10: Automate testing and deployments
* Create automated tests that verify all user-facing functionality
* Create unit and integration tests to verify modules and components
* Run tests automatically as part of the build process
* Perform deployments automatically with deployment scripts, continuous delivery services, or similar techniques
* Conduct load and performance tests at regular intervals, including before public launch

**Comment by JXPrime** [comment]
Other relevant commits: 1463eecb1200514305a5258ddcc55449091359c6

**Comment by JXPrime** [comment]
77251a588c6aeb2407558294f2c071f1bcee11d6
cdcec3e1ac508631bc56749d7827e9178c01a445
74cef093f4d6b57452c197045f25103a243f9d3a
9ba338cf0cabbe149019eb2ff8ad130493d40dba
4bf79003a1102dc4b682bb31e925eac866877612
56a5d399a4e8d28c3218d4bed794bd5c40e2d6a8

**Comment by ClaireReinken** [comment]
FEi used X-Unit to write unit tests for the ASP.Net Core Business Logic. Our unit tests can be found in https://github.com/FEISystems/ca-adpq-prototype/tree/master/ca_proto/ca_proto_tests.
The screenshot below shows Unit Test Runner results.
