### ISSUE TITLE
Setup or used a continuous integration system to automate the running of tests

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#56]
Setup or used a continuous integration system to automate the running of tests and continuously deployed their code to their IaaS or PaaS provider

**Comment by ryan-chadwick-fei** [comment]
This is baked into the automatic builds.  'dotnet test' is run on the x-unit framework when the build is run.

This executes all the unit tests that have been written in the ca_proto_tests project.
