### ISSUE TITLE
Setup or used continuous monitoring

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#58]
Setup or used continuous monitoring

**Comment by ryan-chadwick-fei** [comment]
this is parent issue to
[Implement a Log Management System #78](https://github.com/FEISystems/ca-adpq-prototype/issues/78)
and
[Implement a Monitoring and Alerting System #75](https://github.com/FEISystems/ca-adpq-prototype/issues/75)

**Comment by ryan-chadwick-fei** [comment]
[Grafana Metric and Analytic Dashboard](http://ca-adpq-prototype.eastus2.cloudapp.azure.com:3000)

[Prometheus Monitoring Server](http://ca-adpq-prototype.eastus2.cloudapp.azure.com:9090/status)

[DockerDash Docker Engine Dashboard](http://ca-adpq-prototype.eastus2.cloudapp.azure.com:5050)
