### ISSUE TITLE
Deployed their software in an open source container, such as Docker 

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#59]
Deployed their software in an open source container, such as Docker (i.e., utilized operating-system-level virtualization)

child issues:

[Automate Builds of MySQL Docker Image with base config #138](https://github.com/FEISystems/ca-adpq-prototype/issues/138)

[Build CI/CD Environment - Automatic Builds of :stable Docker Image using Docker Hub #127](https://github.com/FEISystems/ca-adpq-prototype/issues/127)

[Build CI/CD Environment - Automatic Builds of :latest Docker Image using Docker Hub #128](https://github.com/FEISystems/ca-adpq-prototype/issues/128)

**Comment by ryan-chadwick-fei** [comment]
Deployments have been entirely Docker based from the get-go

https://hub.docker.com/u/feidevops/dashboard/
