### ISSUE TITLE
Used at least a minimum of three (3) “user-centric design” techniques and/or tools

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#61]
Used at least a minimum of three (3) “user-centric design” techniques and/or tools

**Comment by lutech** [comment]
The following techniques and/or tools were used for the design process of the prototype:

- User Journey Map
- Visualization of app using Axure Prototyping Tool
- Hi-Fidelity UI Theme Mockups
- User Testing using Axure Prototype
