### ISSUE TITLE
Assigned one (1) leader and gave that person authority and responsibility

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#63]
Assigned one (1) leader and gave that person authority and responsibility and held that person accountable for the quality of the prototype submitted;
Digital Play 6: Assign one leader and hold that person accountable
* A product owner has been identified
* All stakeholders agree that the product owner has the authority to assign tasks and make decisions about features and technical implementation details
* The product owner has a product management background with technical experience to assess alternatives and weigh tradeoffs
* The product owner has a work plan that includes budget estimates and identifies funding sources
* The product owner has a strong relationship with the contracting officer

**Comment by llin-freeman** [comment]
Done when assembling team.
