### ISSUE TITLE
Assembled a multidisciplinary and collaborative team 

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#64]
Assembled a multidisciplinary and collaborative team that includes, at a minimum, five (5) of the labor categories as identified in Attachment B: PQVP DS-AD Labor Category Descriptions
Digital Play 7: Bring in experienced teams
* Member(s) of the team have experience building popular, high-traffic digital services
* Member(s) of the team have experience designing mobile and web applications
*Member(s) of the team have experience using automated testing frameworks
* Member(s) of the team have experience with modern development and operations (DevOps) techniques like continuous integration and continuous deployment
* Member(s) of the team have experience securing digital services
* A Federal contracting officer is on the internal team if a third party will be used for development work
* A Federal budget officer is on the internal team or is a partner
* The appropriate privacy, civil liberties, and/or legal advisor for the department or agency is a partner

**Comment by llin-freeman** [comment]
We assembled the team after the RFI was released.
