### ISSUE TITLE
Vendors must include a publicly-available URL for the prototype

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ca-adpq-prototype#65]
Digital Play 9: Deploy in flexible hosting environment
* Resources are provisioned on demand
* Resources scale based on real-time user demand
* Resources are provisioned through an API
* Resources are available in multiple regions
* We only pay for resources we use
* Static assets are served through a content delivery network
* Application is hosted on commodity hardware

**Comment by ryan-chadwick-fei** [comment]
Im taking this one - need to run it through IT CCB - needs DNS and Firewall
need to add configuration for SSL
certificate and domain/sub-domain - most likely going to use ca-adpq-prototype@feisystems.com

**Comment by llin-freeman** [comment]
Hi Ryan,
Let us know when this is ready and what the public URL is.

Thanks!


Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Feb 24, 2017 at 12:59 PM -0500, "Ryan Chadwick" <notifications@github.com<mailto:notifications@github.com>> wrote:


Im taking this one - need to run it through IT CCB - needs DNS and Firewall
need to add configuration for SSL
certificate and domain/sub-domain - most likely going to use ca-adpq-prototype@feisystems.com<mailto:ca-adpq-prototype@feisystems.com>

**Comment by ryan-chadwick-fei** [comment]
http://ca-adpq-prototype.eastus2.cloudapp.azure.com
