### ISSUE TITLE
Admin User Story 2 - Add Items to Catalog

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#7]
As an administrator, I want to be able to add products and services provided by state contracted vendors to the catalog so consumers can order item(s) they want 

Acceptance Criteria:
•	User can access a screen to add items one at a time
•	Screen contains the following fields:
- CLIN [text]
- UNPSC Code (Version 11) [text]
- Manufacturer Part Number (OEM #) [text]
- Manufacturer (OEM) [text]
- SKU #/ Item # [text]
- Item Name [text]
- Item Description [text]
- Unit of Measure (if applicable) [dropdown - EACH or HOURS]
- List Price/MSRP [dollar]
- Contract Unit Price [dollar]
- Contract Discount [percentage]
- Category [predictive text dropdown]
- Product Type [dropdown - HARDWARE / SOFTWARE / SERVICE]
- Contract # [text]
- Contract Vendor [text]
- Contract Expiration Date [date]
- Product Image -  browse for an image

•	User can preview the item content of the catalog
•	User can save
•	User can cancel

**Comment by neelusingh28** [comment]
Should we also add following two in above list?
UNSPSC Code 
Product Name

**Comment by neelusingh28** [comment]
Can admin also modify catalog after publishing? will there be an edit option?

**Comment by ClaireReinken** [comment]
Can admin also modify catalog after publishing? will there be an edit option? - Yes. They should be able to edit any item including the ability to delete it after its published

**Comment by ClaireReinken** [comment]
Should we also add following two in above list?
 UNSPSC Code
 Product Name

**Comment by ClaireReinken** [comment]
Should we also add following two in above list?
 UNSPSC Code - Yes, I updated the user story above
 Product Name - Yes, I updated the user story above.

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues #102 and #103

**Comment by davidatfei** [comment]
This is implemented and testable. However, the db schema is from early in the week. Some work still needs to be done to include changes that were made to the db schema this week.

**Comment by jennymnh** [comment]
What would go under the categories dropdown?
Software, Hardware, and Services? Or do we want to list every type of hardware/service (standard desktops/power desktops/value added services/etc)?

Also, is there any reason (maybe it's a typo?) that many of these items are sub items on the list?
![image](https://cloud.githubusercontent.com/assets/9370407/23098048/2807315e-f612-11e6-9ba4-fc4774c4758c.png)

**Comment by jennymnh** [comment]
Another question, is searching implied? How would an admin know which items are available to modify?

If a search page is implied, which filter fields would show up on the search page?

**Comment by ClaireReinken** [comment]
Another question, is searching implied? How would an admin know which items are available to modify? - Good question. The admin should be able to search existing catalog items so they can be modified

If a search page is implied, which filter fields would show up on the search page? - All: "columns" in the data set provided by Lisa. For example, CLIN, Product name, product type, SKU, etc.

**Comment by jennymnh** [comment]
Thank you for your replies. I have a few other questions.

Based on the Prototype A Resources excel file sent by CA, I am not seeing some of these acceptance criteria fields in the excel document.

- Vendor/Supplier - Is this the same as contractor?
- Contract End Date (I see an effective date but no end date? Screenshot below)
![image](https://cloud.githubusercontent.com/assets/9370407/23108324/c333c21a-f6d9-11e6-848f-84100a8d4c76.png)

We also need to determine which of these filter fields will show once the search results appear. I don't think listing all of them in a table would work very well.

**Comment by ClaireReinken** [comment]
See below

- Claire Reinken

On Feb 19, 2017, at 7:29 PM, Jenny Ho <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your replies. I have a few other questions.

Based on the Prototype A Resources excel file sent by CA, I am not seeing some of these acceptance criteria fields in the excel document.

  *   Vendor/Supplier - Is this the same as contractor? - correct
  *   Contract End Date (I see an effective date but no end date? Screenshot below) - I need to talk to Lisa to see if she can create this row in the data set or if we will exclude it.
[image]<https://cloud.githubusercontent.com/assets/9370407/23108324/c333c21a-f6d9-11e6-848f-84100a8d4c76.png>

-

**Comment by lutech** [comment]
@ClaireReinken - I spoke to Dave on how to handle uploading images. Since the customer doesn't have a column for images in their data set, I think we should allow them to do a separate bulk import of images (like a whole folder). Then, the user will have to edit each product and choose what image to associate from a drop down (options will be driven by images that are uploaded - which should be limited to .JPG and .PNG only). Finally, for our test data, I can manually edit the products in the csv file to use the correct image so we don't have to do it one by one in the app.  Are you ok with this? Also, Dave may be able to display the image to the user as they make their selection.  Let me know if this makes sense or if you need a further explanation.

**Comment by ClaireReinken** [comment]
@lutech  and @davidatfei Let's write instructions for the admin user that indicates to bulk import images in this feature, they need to add a column to their data set, named "x" and add the name of the image file. If they can't include this information, then they can go back and edit each item and browse for an image. Agree images should be limited to .JPG or .PNG.

**Comment by ClaireReinken** [comment]
Moving to QC Sprint 3

**Comment by neelusingh28** [comment]
Tested on 5000 url:

1. User cannot preview the item before adding. Is that expected?
2. There is NO cancel button. Is that expected?

**Comment by ClaireReinken** [comment]
Tested on 5000 url:
1.User cannot preview the item before adding. Is that expected? - I am going to write a separate issue for this functionality. 
2.There is NO cancel button. Is that expected? - That's fine.

**Comment by neelusingh28** [comment]
Verified and Passed in 5000 site and in Firefox too.
