### ISSUE TITLE
Admin User Story 4 - Delete Products and Services from Catalog

### ISSUE THREAD

**Issue by cbgordon** [FEISystems/ca-adpq-prototype#8]
As an administrator, I want to delete products and services from the catalog so I can ensure items that aren’t available for ordering do not appear

Acceptance Criteria:
•	User can remove an item from the catalog

**Comment by neelusingh28** [comment]
Q1. Once products and services are deleted by admin I'm expecting that when user will perform search for those items then system will display error message that these products or services are no more available?

Q2. Will there be any additional info too that we will notify you on your email once these products or services will be available?

**Comment by ClaireReinken** [comment]
Dev and UI tasks are included in Issues @104 and #105

**Comment by davidatfei** [comment]
This feature is implemented and testable. Some UI styling still needs to occur.

**Comment by Mikewilburn302** [comment]
Is there going to be a way to remove items in bulk? If a contract expires, the user will have to manually remove hundreds of items individually which is not particularly efficient.

**Comment by ClaireReinken** [comment]
Is there going to be a way to remove items in bulk? If a contract expires, the user will have to manually remove hundreds of items individually which is not particularly efficient. - Yes, in a way. The admin will be able to check multiple items to delete though. Stand by for a revised user story later today.

**Comment by ClaireReinken** [comment]
Duplicate to Issue #115
